### ISSUE TITLE
red squiggly 'error lines' under block comments

### ISSUE THREAD

**Issue by Welchd1** [Welchd1/resolve-intellij-plugin#12]
Like the title says: for some reason the psi recognize the comment style (i can see the node in psi viewer), but underlines them as errors anyways.

**Comment by EsmeK** [comment]
I noticed that Block comments weren't in the RESOLVETokenTypes file. Adding them seems to have fixed the issue for me.

**Comment by Welchd1** [comment]
k, think you could incorporate ur fix in a fresh branch of the most recent master, submit a pull request that fixes it and I'll go ahead and test it out on my end?

**Comment by Welchd1** [comment]
Fixed as of #9
