### ISSUE TITLE
code folding

### ISSUE THREAD

**Issue by Welchd1** [Welchd1/resolve-intellij-plugin#8]
Code folding for procedure decls, comments, and perhaps record types.

**Comment by Welchd1** [comment]
Initial folding complete. We still need folding for several major constructs including type models, type representations, and facility decls (with enhancements)

**Comment by EsmeK** [comment]
Added folding for type models, type representations and facility decls (enhancements get folding inside, showing only Facility NAME... currently)

**Comment by Welchd1** [comment]
kool

**Comment by Welchd1** [comment]
Initial version added with a good number (basically all constructs) supported. Missing constructs can now be addressed by individual issues/bug reports.
